# Generated by Django 2.2.3 on 2019-08-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20190827_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifeline1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='stack',
            field=models.IntegerField(default=0),
        ),
    ]
