# Generated by Django 2.2.3 on 2019-08-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='string',
            old_name='use_life',
            new_name='str',
        ),
    ]
