# Generated by Django 2.2.3 on 2019-08-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20190829_0928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='String',
        ),
        migrations.AddField(
            model_name='profile',
            name='lifeline2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ll_counter',
            field=models.IntegerField(default=4),
        ),
    ]
